// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPIdbZo7h1wgTOfdlQdq4yjdse9ud56mA',
    appId: '1:574977043591:web:6d0d69e4772b522d1ddc22',
    messagingSenderId: '574977043591',
    projectId: 'oracletestapp',
    authDomain: 'oracletestapp.firebaseapp.com',
    storageBucket: 'oracletestapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChtM_1ekX0aaeuM2UviOMw_u7HtGquKo8',
    appId: '1:574977043591:android:65b9f6cf1e08b7ab1ddc22',
    messagingSenderId: '574977043591',
    projectId: 'oracletestapp',
    storageBucket: 'oracletestapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyb9Z3r6VH0hzOypD1xKQSJ-k96l1Cci0',
    appId: '1:574977043591:ios:726cff79a58a87771ddc22',
    messagingSenderId: '574977043591',
    projectId: 'oracletestapp',
    storageBucket: 'oracletestapp.appspot.com',
    iosBundleId: 'com.example.oracleApp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyb9Z3r6VH0hzOypD1xKQSJ-k96l1Cci0',
    appId: '1:574977043591:ios:bce26f192a48e9b41ddc22',
    messagingSenderId: '574977043591',
    projectId: 'oracletestapp',
    storageBucket: 'oracletestapp.appspot.com',
    iosBundleId: 'com.example.oracleApp2.RunnerTests',
  );
}
